version: '3.8'
services:
  fitbitWeightServer:
    container_name: fitbit_weight_server
#    image: ghcr.io/TomW1605/controllerv2
    build: ./
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src
    restart: unless-stopped
